version: "3.8"

services:
  # База данных для hookah-версии
  db_hookah:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5440:5432"
    volumes:
      - postgres_data_hookah:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Инициализация схемы для hookah-базы
  database-init-hookah:
    build: ./service-database
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db_hookah
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    depends_on:
      db_hookah:
        condition: service_healthy

  # Gateway hookah
  gateway_hookah:
    build: ./gateway
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db_hookah
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    ports:
      - "4004:4000"
    depends_on:
      - db_hookah
      - database-init-hookah

  # Auth hookah
  auth_hookah:
    build: ./service-auth
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db_hookah
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    ports:
      - "3004:3000"
    depends_on:
      - db_hookah
      - database-init-hookah

  # Calendar hookah
  calendar_hookah:
    build: ./service-calendar
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db_hookah
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      TELEGRAM_BOT_SERVICE: "telegram-bot-hookah:5000"
      WHATSAPP_SERVICE_URL: "whatsapp-code-sender-hookah:7001"
    ports:
      - "8004:8000"
    depends_on:
      - db_hookah
      - database-init-hookah

  # Telegram Bot hookah (Info)
  telegram-bot-hookah:
    build: ./service-telegram-bot
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN_INFO: ${TELEGRAM_BOT_TOKEN_INFO}
      SERVICE_CALENDAR_URL: "calendar_hookah:8000"
    ports:
      - "5004:5000"
    depends_on:
      - calendar_hookah

  # Telegram Code Sender hookah
  telegram-code-sender-hookah:
    build: ./service-telegram-code-sender
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db_hookah
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
      - "7006:7000"
    depends_on:
      - db_hookah
      - database-init-hookah

  # WhatsApp Code Sender hookah
  whatsapp-code-sender-hookah:
    build: ./service-whatsapp-code-sender
    env_file:
      - .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    ports:
      - "7007:7001"
    volumes:
      - whatsapp-session-hookah:/app/.wwebjs_auth
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    depends_on:
      - db_hookah
      - database-init-hookah

  telegram-bot-group-hookah:
    build: ./service-telegram-bot-group
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN_GROUP: ${TELEGRAM_BOT_TOKEN_GROUP}
    ports:
      - "8020:8020"
    depends_on:
      - calendar_hookah

volumes:
  postgres_data_hookah:
  whatsapp-session-hookah:
