version: '3.8'

services:
  # Test DB (порт внешнего хоста отличается от основного)
  db:
    image: postgres:13
    env_file:
      - .env             # или .env.test, если хотите отдельные креденшелы
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5439:5432"       # тестовый порт 5439 вместо 5438
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Инициализация схемы
  database-init:
    build: ./service-database
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  # Test Gateway
  gateway:
    build: ./gateway
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    ports:
      - "4001:4000"       # внешний 4001 → внутренний 4000
    depends_on:
      - db
      - database-init

  # Test Auth
  auth:
    build: ./service-auth
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    ports:
      - "3001:3000"
    depends_on:
      - db
      - database-init

  # Test Calendar
  calendar:
    build: ./service-calendar
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      TELEGRAM_BOT_SERVICE: "telegram-bot:5001"
    ports:
      - "8001:8000"
    depends_on:
      - db
      - database-init

  # Test Telegram Bot
  telegram-bot:
    build: ./service-telegram-bot
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN_INFO: ${TELEGRAM_BOT_TOKEN_INFO}
      SERVICE_CALENDAR_URL: "calendar:8001"
    ports:
      - "5001:5000"
    depends_on:
      - calendar

  # Test Telegram Code Sender
  telegram-code-sender:
    build: ./service-telegram-code-sender
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
      - "7002:7000"
    depends_on:
      - db
      - database-init

  # Test WhatsApp Code Sender
  whatsapp-code-sender:
    build: ./service-whatsapp-code-sender
    env_file:
      - .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    ports:
      - "7003:7001"
    volumes:
      - whatsapp-session-test:/app/.wwebjs_auth
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    depends_on:
      - db
      - database-init

volumes:
  postgres_data_test:
  whatsapp-session-test:
