services:
  test-db:
    container_name: test-db
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: test_${POSTGRES_DB}
    ports:
      - "5439:5433"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d test_${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - test-network

  test-database-init:
    container_name: test-database-init
    build: ./service-database
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: test-db
      DB_NAME: test_${DB_NAME}
      DB_PORT: 5432
    depends_on:
      test-db:
        condition: service_healthy
    networks:
      - test-network

  test-gateway:
    container_name: test-gateway
    build: ./gateway
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: test-db
      DB_NAME: test_${DB_NAME}
      DB_PORT: 5432
    ports:
      - "4002:4001"
    depends_on:
      test-db:
        condition: service_healthy
      test-database-init:
        condition: service_completed_successfully
    networks:
      - test-network

  test-auth:
    container_name: test-auth
    build: ./service-auth
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: test-db
      DB_NAME: test_${DB_NAME}
      DB_PORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      test-db:
        condition: service_healthy
      test-database-init:
        condition: service_completed_successfully
    networks:
      - test-network

  test-calendar:
    container_name: test-calendar
    build: ./service-calendar
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: test-db
      DB_NAME: test_${DB_NAME}
      DB_PORT: 5432
    ports:
      - "8001:8001"
    depends_on:
      test-db:
        condition: service_healthy
      test-database-init:
        condition: service_completed_successfully
    networks:
      - test-network

  test-telegram-bot:
    container_name: test-telegram-bot
    build: ./service-telegram-bot
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: test-db
      DB_NAME: test_${DB_NAME}
      DB_PORT: 5432
    depends_on:
      test-db:
        condition: service_healthy
      test-database-init:
        condition: service_completed_successfully
    networks:
      - test-network

  test-parser:
    container_name: test-parser
    build: ./service-parser
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: test-db
      DB_NAME: test_${DB_NAME}
      DB_PORT: 5432
    depends_on:
      test-db:
        condition: service_healthy
      test-database-init:
        condition: service_completed_successfully
    networks:
      - test-network

  test-telegram-code-sender:
    container_name: test-telegram-code-sender
    build: ./service-telegram-code-sender
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: test-db
      DB_NAME: test_${DB_NAME}
      DB_PORT: 5432
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
      - "7001:7001"
    depends_on:
      test-db:
        condition: service_healthy
      test-database-init:
        condition: service_completed_successfully
    networks:
      - test-network

  test-whatsapp-code-sender:
    container_name: test-whatsapp-code-sender
    build: ./service-whatsapp-code-sender
    env_file:
      - .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    ports:
      - "7003:7003"
    volumes:
      - test_whatsapp-session:/app/.wwebjs_auth
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    depends_on:
      test-db:
        condition: service_healthy
      test-database-init:
        condition: service_completed_successfully
    networks:
      - test-network

volumes:
  test_postgres_data:
  test_whatsapp-session:

networks:
  test-network:
    name: test-network